In [37]:
%pip install transformers

     ---------------------------------------- 0.0/44.1 kB ? eta -:--:--
     ----------------- -------------------- 20.5/44.1 kB 330.3 kB/s eta 0:00:01
     -------------------------------------- 44.1/44.1 kB 546.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.4/10.0 MB 8.1 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/10.0 MB 9.8 MB/s eta 0:00:01
   ----- ---------------------------------- 1.3/10.0 MB 9.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.0/10.0 MB 10.6 MB/s eta 0:00:01
   ---------- ----------------------------- 2.5/10.0 MB 10.7 MB/s eta 0:00:01
   ------------ --------------------------- 3.1/10.0 MB 11.5 MB/s eta 0:00:01
   -------------- ------------------------- 3.6/10.0 MB 11.4 MB/s eta 0:00:01
   ---------------- ----------------------- 4.1/10.0 MB 11.5 MB/s eta 0:00:01
   ------------------ --------------------- 4.6/10.0 MB 11.4 MB/s eta 0:00:01

In [3]:
import torch

# Define the mask tensor
mask = torch.tensor(
  [  
    [1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0],
    [1, 1, 1, 1, 1, 1] 
  ])  # Shape: (1, 6, 6)

# Define a sample input tensor for the decoder (batch_size=1, seq_len=6, vector_dim=4)
input_tensor = torch.randn(1, 6, 4)

# Applying the mask to the input tensor
# Simulating the mask application by setting masked elements to zero based on the attention mask
masked_output = input_tensor * mask.unsqueeze(-1)

# Display the result
input_tensor, masked_output, mask.unsqueeze(1)

(tensor([[[-0.1165,  0.0403, -0.3077, -1.2563],
          [ 0.2136, -1.6072,  0.5230,  1.4587],
          [ 2.4053,  0.8354, -0.4058, -0.1202],
          [ 1.2923,  1.0156, -1.4036, -1.1738],
          [-0.9638, -0.4862, -2.7030, -1.1667],
          [ 0.5169,  1.2041,  0.1021, -0.5893]]]),
 tensor([[[[-0.1165,  0.0403, -0.3077, -1.2563],
           [ 0.0000, -0.0000,  0.0000,  0.0000],
           [ 0.0000,  0.0000, -0.0000, -0.0000],
           [ 0.0000,  0.0000, -0.0000, -0.0000],
           [-0.0000, -0.0000, -0.0000, -0.0000],
           [ 0.0000,  0.0000,  0.0000, -0.0000]],
 
          [[-0.1165,  0.0403, -0.3077, -1.2563],
           [ 0.2136, -1.6072,  0.5230,  1.4587],
           [ 0.0000,  0.0000, -0.0000, -0.0000],
           [ 0.0000,  0.0000, -0.0000, -0.0000],
           [-0.0000, -0.0000, -0.0000, -0.0000],
           [ 0.0000,  0.0000,  0.0000, -0.0000]],
 
          [[-0.1165,  0.0403, -0.3077, -1.2563],
           [ 0.2136, -1.6072,  0.5230,  1.4587],
           [ 2.40

In [35]:
import torch
import torch.nn as nn

# vocab 크기와 임베딩 차원 설정
vocab_size = 10
embedding_dim = 3
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

# 단어 인덱스 0~9999까지 임베딩 가능
input_indices = torch.tensor([0, 3, 8])
output = embedding_layer(input_indices)
print(output)  # 각 인덱스에 해당하는 512차원 임베딩 벡터 출력

tensor([[-1.5451, -0.9219, -0.0328],
        [-0.1412, -0.7991,  1.4858],
        [ 0.0860,  0.3880,  0.3223]], grad_fn=<EmbeddingBackward0>)


In [38]:
from transformers import AutoTokenizer

# 예시 토크나이저 로드 (BERT 토크나이저)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# 텍스트를 토큰화하고 텐서로 변환
input_text = "I love NLP"
tokens = tokenizer.tokenize(input_text)
indices = tokenizer.convert_tokens_to_ids(tokens)

# 직접 텐서로 변환
tensor = torch.tensor(indices)
print("토큰:", tokens)
print("인덱스:", indices)
print("텐서:", tensor)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

c:\Users\pqstv\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\pqstv\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

토큰: ['i', 'love', 'nl', '##p']
인덱스: [1045, 2293, 17953, 2361]
텐서: tensor([ 1045,  2293, 17953,  2361])
